### PR TITLE
Create the skeleton type php_file

### PR DESCRIPTION
**Pull request by alexandru-elisei**

### CODE REVIEW

**Comment by mudrd8mz** [comment]
* Firstly, I was hoping to find a good alternative to `php_internal_file`. I am not sure that `php_external_file` would be a good name. Maybe we could have `php_web_file` for files that are supposed to be visited by the web, `php_cli_file` for CLI scripts and `php_ajax_file` for AJAX scripts.
* Why do you think that db/install.php and db/uninstall.pho should not be internal?

**Comment by alexandru-elisei** [comment]
About me thinking that db/install.php and db/uninstall.php should not be internal. Been looking at [your moodle-mod_newmodule](https://github.com/moodlehq/moodle-mod_newmodule/blob/master/db/install.php) and [justin hunt's moodle-mod_newmodule](https://github.com/justinhunt/moodle-mod_newmodule/blob/master/db/install.php) and the files aren't moodle internal.

But after looking at the same files that come with official moodle plugins they are defined as moodle internal.

What is right? Now I am leaning towards making them internal.

**Comment by alexandru-elisei** [comment]
I don't think php_web_file is a good name. Is lib.php supposed to be visited from the web site? Because it is moodle internal.

**Comment by alexandru-elisei** [comment]
I personally like php_internal_file. It's very obvious what it is.

**Comment by mudrd8mz** [comment]
> I don't think php_web_file is a good name. Is lib.php supposed to be visited from the web site? Because it is moodle internal. 

I do not think we are on the same wave here. Let me try and explain things better.

Up until Moodle 2.9 there were four basic sorts of PHP files used in Moodle.

* Files that are accessed by the browser when serving normal HTTP request, such as index.php files or mod/whatever/view.php file. These files are not for CLI execution. They must always require the main config.php as the first thing as a part of environment bootstrapping. In my proposal, I suggest to use `php_web_file` skeleton class.
* Files that are never accessed directly by the browser, they are only included by other PHP files. These files do not require the main config.php - instead they only check for the MOODLE_INTERNAL constant (which is set during the environment bootstrapping). This is what `php_internal_file` skeleton class does.
* CLI scripts can be executed from CLI only, not from the web. They must define the CLI_SCRIPT constant and then include the main config.php file as the first thing. It makes sense if they require the clilib.php by default, too.
* Finally there were AJAX scripts that had to define AJAX_SCRIPT before config.php. But we will skip these as this method of implementing AJAX in Moodle has been deprecated with Moodle 2.9 (https://docs.moodle.org/dev/AJAX_pre_2.9).

So we end up with three sorts of PHP files: web, internal and cli.

All db/*.php are internal. All lib.php are internal.

**Comment by mudrd8mz** [comment]
And yes, sometimes templates that are used around the world forget to start with the MOODLE_INTERNAL check. That is why this our tool does a better job than others as it forces us to explicitly say what sort of PHP file each one is.

**Comment by alexandru-elisei** [comment]
I understand now, reject this pull request and I'll create one with the proposed file classes.

**Comment by alexandru-elisei** [comment]
After you're done with this round of merges I'll update the skel classes to use the correct base class.

**Pull request closed without merging**
