### PR TITLE
Cli_script feature

### PR DESCRIPTION
**Pull request by alexandru-elisei**
Modified based on the comments in #29.

After this gets merged I'll remove the 'all' feature from all the PHPUnit files.

### CODE REVIEW

**Comment by mudrd8mz** [comment]
Note, I am once again worried about adding things like support for `$this->recipe['cli_script']` without having a single place (recipe-dist.yaml) where every single supported value would be put and documented. It will be a painful, boring and error prone process to construct such a file later.

**Comment by mudrd8mz** [comment]
Can you please rebase to avoid conflicts.

**Comment by alexandru-elisei** [comment]
Rebased.

**Comment by mudrd8mz** [comment]
May I ask for yet another modification please. Can the recipe file option read `cli_scripts` (plural) to be consistent with other keywords we use there to describe lists (such as capabilities, message_providers, strings etc). 

Also, this patch should probably remove the note "Not implemented yet." from the referential example.yaml recipe.

**Comment by mudrd8mz** [comment]
I am going to close this pull request now. Can you please make a new one with the suggested changes. I would like to test the newly set up travis integration with https://travis-ci.org/mudrd8mz/moodle-tool_pluginskel/ which should automatically run the unit tests and coding style checkers for every new pull request. Thanks for understanding.

**Pull request closed without merging**
