### PR TITLE
Add generator for Tiny plugintype

### PR DESCRIPTION
**Pull request by andrewnicols**
This is still a work-in-progress, but I wanted to put it out there to start with.

Currently missing:
* unit tests
* some strings for the UI
* some changes to the Tiny API which I may make shortly.

### CODE REVIEW

**Comment by andrewnicols** [comment]
Okay,

I think I've got this finished for now. I won't submit it for review just yet until we've confirmed that the Moodle side of the Tiny API is stable. Once we've confirmed that, then this PR is ready for review.

**Comment by mudrd8mz** [comment]
Yay, great to see more quality and referential JS like this. Many thanks Andrew.

I'll wait for your confirmation of the stable API.

**Comment by andrewnicols** [comment]
API is now stable and I believe that this is now ready. Huzzah!

I'm sure there will be improvements to the generated code over time, but this is a good start.

In particular, there may wellbe improvements to the icon side of things, but I can't think of a good way of handling this right now.

**Comment by alexmorrisnz** [comment]
Hi @mudrd8mz @andrewnicols This hasn't been merged yet but the new Moodle dev docs for creating a Tiny plugin were updated to include instructions that don't work without this PR
Can it be merged? I've tested and it seems fine

**Comment by mudrd8mz** [comment]
Sorry my bad. I'd lost this from my radar.

**Comment by mudrd8mz** [comment]
For the record, this is now part of the 1.6.0 version.

**Pull request merged**
