### PR TITLE
Use verify_strings_exist()

### PR DESCRIPTION
**Pull request by alexandru-elisei**

### CODE REVIEW

**Comment by alexandru-elisei** [comment]
The error is the same setUpBeforeClass() function name error.

Is there some way for me to fix this?

**Comment by mudrd8mz** [comment]
I am not aware of a way to deal with this one particular false travis error on our side. The only option I know is to ignore all tests from all the checks. We can probably do that.

**Comment by alexandru-elisei** [comment]
No, those tests are important. I can live with always having to check the cause of the error for each pull request.

**Comment by mudrd8mz** [comment]
I am not saying the tests won't be executed. But the files in tests/* will be skipped from the checks like syntax etc. I committed this temporary fix already in our travis file. I also opened https://github.com/moodlehq/moodle-local_codechecker/pull/31 for the permanent and proper solution. Once the code checker fix is accepted and deployed, we will undo our workaround.

**Comment by alexandru-elisei** [comment]
Oh, I see now. Yes, this is a good idea.

**Comment by mudrd8mz** [comment]
https://travis-ci.org/mudrd8mz/moodle-tool_pluginskel/jobs/144418877 started to pass again.

**Pull request merged**
